MTDSA=6217 update models for tax calc
hmrc/individual-calculations pull request #85
Opened 2020-09-14 14:05 UTC by yangwong9664

2020-09-15 09:36 UTC, BetaDraconis requested changes
Some issues with field typings, field name mappings, field value mappings, missing empty item mappings, missing test classes. Test data will also need to be updated as per requested changes.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/Reliefs.scala
> +                     foreignTaxCreditRelief: Option[ForeignTaxCreditRelief],
This should be an array.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/Reliefs.scala
> +                     reliefsClaimed: Option[ReliefsClaimed]
This should also be an array.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/Reliefs.scala
> +      (JsPath \ "calculation" \ "reliefs" \ "foreignTaxCreditRelief").readNestedNullable(ForeignTaxCreditRelief.reads) and
```suggestion
      (JsPath \ "calculation" \ "reliefs" \ "foreignTaxCreditRelief").readNestedNullable[Seq[ForeignTaxCreditRelief]] and
```

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/Reliefs.scala
> +      (JsPath \ "calculation" \ "reliefs" \ "reliefsClaimed").readNestedNullable(ReliefsClaimed.reads)
```suggestion
      (JsPath \ "calculation" \ "reliefs" \ "reliefsClaimed").readNestedNullable[Seq[ReliefsClaimed]]
```

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ForeignTaxCreditRelief.scala
> +                                   incomeSourceType: Option[BigInt],
This is a String.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ForeignTaxCreditRelief.scala
> +                                   countryCode: Option[BigInt],
These fields are also strings.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ForeignTaxCreditRelief.scala
> +                                   amountUsed: Option[BigInt]
These fields should be decimals.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ForeignTaxCreditRelief.scala
> +    (JsPath \ "incomeSourceType").readNestedNullable[BigInt] and
This field needs mapping from DES enum (i.e "01", "02", "04") to MTD enum (i.e "self-employment", "non-fhl", "fhl") as per the spec.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ForeignTaxCreditRelief.scala
> +      (JsPath \ "countryCode").readNestedNullable[BigInt] and
These are strings.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ForeignTaxCreditRelief.scala
> +      (JsPath \ "amountUsed").readNestedNullable[BigInt]
These are decimals.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ForeignTaxCreditRelief.scala
> +      (JsPath \ "amountUsed").readNestedNullable[BigInt]
Should just be 'readNullable' since these fields aren't nested.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/PensionContributionReliefs.scala
> +                                       oneOffPensionContributionsPaid: Option[BigInt]
Should all be decimals.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/PensionContributionReliefs.scala
> +    (JsPath \ "totalPensionContributionReliefs").readNestedNullable[BigInt] and
Should just be 'readNullable' since the field isn't nested.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/PensionContributionReliefs.scala
> +      (JsPath \ "pensionContributionDetail" \ "oneOffPensionContributionsPaid").readNestedNullable[BigInt]
All of these are decimals.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/Reliefs.scala
> +      (JsPath \ "calculation" \ "reliefs" \ "reliefsClaimed").readNestedNullable(ReliefsClaimed.reads)
Similarly for the allowances case class, these objects/ array objects contain only empty items so require mapping to remove potential empty items. The array fields also require mapping to remove potential empty arrays (.mapEmptySeqToNone).

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ReliefsClaimed.scala
> +                           `type`: Option[BigInt],
This field is a string.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ReliefsClaimed.scala
> +                           rate: Option[BigInt]
These fields are decimals.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ReliefsClaimed.scala
> +    (JsPath \ "type").readNestedNullable[BigInt] and
Requires some minor name mapping as per the spec ("Note the downstream specs use 'nonDeductableLoanInterest'. We need to return 'nonDeductibleLoanInterest', which is the correct spelling to use.").

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ReliefsClaimed.scala
> +      (JsPath \ "rate").readNestedNullable[BigInt]
Should just use 'readNullable' since these fields are not nested.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/AnnualPayments.scala
> +case class AnnualPayments(
This case class has no unit tests.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ForeignTaxCreditRelief.scala
> +case class ForeignTaxCreditRelief(
This case class has no unit tests.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/PensionContributionReliefs.scala
> +case class PensionContributionReliefs(
This case class has no unit tests.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/PensionContributions.scala
> +case class PensionContributions(
This case class has no unit tests.

2020-09-15 09:36 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ReliefsClaimed.scala
> +case class ReliefsClaimed(
This case class has no unit tests.

2020-09-15 09:36 UTC, BetaDraconis commented on test/v1/models/response/getCalculation/allowancesAndDeductions/detail/ReliefsSpec.scala
> +      Some(1000),Some(1000))))
Test data will need updating as per the model changes.

2020-09-15 09:36 UTC, BetaDraconis commented on test/v1/fixtures/getCalculation/allowancesAndDeductions/detail/ReliefFixtures.scala
>    val desJson: JsValue = Json.parse("""{
Test data will need to be updated as per the requested case class changes.

2020-09-15 09:36 UTC, BetaDraconis commented on test/v1/models/response/getCalculation/allowancesAndDeductions/detail/AllowancesAndDeductionsSpec.scala
> +  val allowancesAndDeductions = AllowancesAndDeductions(Some(1000), Some(1000), Some(1000), Some(1000), Some(1000),
Test data will need updating as per the requested changes.

2020-09-15 09:36 UTC, BetaDraconis commented on test/v1/fixtures/getCalculation/allowancesAndDeductions/detail/CalculationDetailFixtures.scala
> +  val desJson: JsValue = Json.parse(
Test data will need updating as per requested changes.

2020-09-15 09:36 UTC, BetaDraconis commented on test/v1/fixtures/getCalculation/GetCalculationResponseFixtures.scala
>                   |     ],
Test data will need to be updated as per requested changes.

2020-09-15 09:36 UTC, BetaDraconis commented on test/v1/fixtures/getCalculation/allowancesAndDeductions/AllowancesDeductionsAndReliefsFixtures.scala
>    val desJson: JsValue = Json.parse("""{
Test data will need to be updated as per requested changes.

2020-09-15 09:36 UTC, BetaDraconis commented on test/v1/fixtures/getCalculation/allowancesAndDeductions/detail/AllowancesAndDeductionsFixtures.scala
> -      |            "lossesAppliedToGeneralIncome": 1000
Test data will need to be updated as per requested changes.

2020-09-16 09:22 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/AnnualPayments.scala
> +    (JsPath \ "grossAnnuityPayments").readNestedNullable[BigDecimal] and
This should just be `readNullable` since the field isn't nested.

2020-09-16 09:24 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/PensionContributions.scala
> +    (JsPath \ "pensionContributions").readNestedNullable[BigDecimal] and
This should just be readNullable since the field isn't nested.

2020-09-16 09:27 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ForeignTaxCreditRelief.scala
> +      (JsPath \ "amountUsed").readNestedNullable[BigDecimal]
This should just be readNullable since the fields aren't nested.

2020-09-16 09:27 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ForeignTaxCreditRelief.scala
> +    (JsPath \ "incomeSourceType").readNestedNullable[String] and
This field needs to have it's values mapped as per the spec.

2020-09-16 09:29 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/PensionContributionReliefs.scala
> +    (JsPath \ "totalPensionContributionReliefs").readNestedNullable[BigDecimal] and
This should just be readNullable since the field isn't nested.

2020-09-16 09:31 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ReliefsClaimed.scala
> +      (JsPath \ "rate").readNestedNullable[Double]
This should just be readNullable since the fields aren't nested.

2020-09-16 09:31 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ReliefsClaimed.scala
> +    (JsPath \ "type").readNestedNullable[String] and
This field needs value mappings as per the spec.

2020-09-16 09:33 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/Reliefs.scala
> +        case Some(ForeignTaxCreditRelief.empty) => None
The typing here is Option[Seq] and not Option[ForeignTaxCreditRelief] so this filter won't work.

2020-09-16 09:33 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/Reliefs.scala
> +      (JsPath \ "calculation" \ "reliefs" \ "reliefsClaimed").readNestedNullable[Seq[ReliefsClaimed]].map {
The typing here is Option[Seq] and not Option[ReliefsClaimed] so this filter won't work.

2020-09-18 09:25 UTC, BetaDraconis commented on app/utils/NestedJsonReads.scala
> +        case Some(model) if model == empty => None
```suggestion
        case Some(empty) => None
```

2020-09-18 09:41 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ForeignTaxCreditRelief.scala
> +                                   incomeSourceType: Option[IncomeSourceType],
This field is mandatory.

2020-09-18 09:42 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ForeignTaxCreditRelief.scala
> +                                   countryCode: Option[String],
This field is also mandatory.

2020-09-18 09:43 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/PensionContributionReliefs.scala
> +                                       totalPensionContributionReliefs: Option[BigDecimal],
This field is mandatory.

2020-09-18 09:45 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/DesIncomeSourceType.scala
> +sealed trait DesIncomeSourceType {
No testing for this.

2020-09-18 09:46 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/IncomeSourceType.scala
> +sealed trait IncomeSourceType
No testing for this file.

2020-09-18 09:51 UTC, BetaDraconis commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/ReliefsClaimed.scala
> +                           `type`: Option[String],
This field is mandatory.

2020-09-18 09:54 UTC, BetaDraconis commented on app/utils/NestedJsonReads.scala
> +  implicit class OptReadsOps[A](reads: Reads[Option[A]]) {
Can you add some unit tests for these new methods.

2020-09-18 10:06 UTC, yangwong9664 commented on app/utils/NestedJsonReads.scala
> +  implicit class OptReadsOps[A](reads: Reads[Option[A]]) {
these were tested in response model tests, but i can remove them and make explicit NestedJsonReads tests

2020-09-18 10:07 UTC, yangwong9664 commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/IncomeSourceType.scala
> +sealed trait IncomeSourceType
these were tested in response model tests, but i can remove them and make explicit Enum tests

2020-09-18 10:07 UTC, yangwong9664 commented on app/v1/models/response/getCalculation/allowancesAndDeductions/detail/DesIncomeSourceType.scala
> +sealed trait DesIncomeSourceType {
these were tested in response model tests, but i can remove them and make explicit Enum tests

2020-09-18 10:10 UTC, yangwong9664 commented on app/utils/NestedJsonReads.scala
> +        case Some(model) if model == empty => None
this won't work

2020-09-18 13:05 UTC, BetaDraconis approved these changes

2020-09-21 10:01 UTC, merged